baseURL                = 'https://richfan.site/'
languageCode           = 'zh'
title                  = '樊刹'
theme                  = 'shadocs'
defaultContentLanguage = "zh"
enableEmoji            = false
enableGitInfo          = false
metaDataFormat         = "yaml"
publishDir             = "public"


# [Author]
#   name = "Rich Fan"

[module]
  [module.hugoVersion]
    extended = true
    min = '0.112.0'
    max = ''
  [[module.mounts]]
    source = 'asyncapi'
    target = 'static/asyncapi'
  [[module.mounts]]
    source = 'openapi'
    target = 'static/openapi'

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ["HTML", "JSON"]

[markup]
  defaultMarkdownHandler = "goldmark"
  [markup.tableOfContents]
    ordered    = false
    startLevel = 1
    endLevel   = 6
  [markup.goldmark.renderer]
    unsafe = false

[Languages]
  [Languages.zh]
    contentDir   = "content/chinese"
    title        = "樊刹"
    weight       = 1
    languageName = "中文"

  [Languages.en]
    contentDir   = "content/english"
    title        = "Fan Temple"
    weight       = 2
    languageName = "English"

#
# Specific configuration
#
[params]
  logo                    = "logo.svg"
  logoTouch               = "logo.svg"
  image404                = "images/404.gif"
  favicon                 = "favicon.svg"
  faviconmd               = "![Favicon](/favicon.svg)"
  homeLayout              = "onboarding"
  siteContentOrder        = "weight"
  toc                   = true
  # globalBanner          = true
  currentVersion          = "latest"
  latestVersionUrl        = "https://richfan.site/"
  # enforceRefrelLinks    = true
  [params.navbar.shortcuts]
    [params.navbar.shortcuts.example]
      keys     = ["Shift","1"]
      function = "scExample"
  [[params.navbar.versions]]
    name = '最新版本'
    url  = 'https://richfan.site/'
  [[params.navbar.versions]]
    name = '已弃用的版本'
    url  = 'https://richfan.site/404.html'
  [params.taxonomies]
    [params.taxonomies.categories]
      icon = "fa-solid fa-table-cells"
    [params.taxonomies.tags]
      icon = "fa-solid fa-tag"
  [params.versions]
    hugo_min         = "[0.112.0](https://github.com/gohugoio/hugo/releases/tag/v0.112.0)"
    bulma            = "[0.9.4](https://github.com/jgthms/bulma/releases/tag/0.9.4)"
